AllCops:
  DisplayCopNames: true

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

# https://github.com/onk/onkcop/blob/f3283b5/config/rubocop.yml#L283-L289
# > * 警告 120文字
# > * 禁止 160文字
# > のイメージ
Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Style/AsciiComments:
  Enabled: false

# https://github.com/onk/onkcop/blob/f3283b5/config/rubocop.yml#L39-L42
# > scope が違うとか親 module の存在確認が必要とかデメリットはあるが、
# > namespace 付きのクラスはかなり頻繁に作るので簡単に書きたい。
Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
