inherit_gem:
  onkcop:
    - config/rspec.yml

RSpec/DescribedClass:
  Exclude:
    - "spec/requests/*"

# Accepts more deeper nests than default(3).
#   describe 'Class'
#     describe 'method'
#       context 'larger scope (behavior)'
#         context 'smaller scope (parameter)'
RSpec/NestedGroups:
  Max: 4
