inherit_gem:
  onkcop:
    - config/rubocop.yml

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Style/DotPosition:
  EnforcedStyle: leading

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/TrailingCommaInLiteral:
  Enabled: true
  EnforcedStyleForMultiline: no_comma
