on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
jobs:
  spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          bundler-cache: true
      - run: bundle exec rake rspec
